### ISSUE TITLE
Afficher les tests par défaut

### ISSUE THREAD

**Issue by mkebri** [DISIC/rgaa_referentiel_3-2016#41]
Afin de pouvoir rediriger vers un test spécifique, par exemple : le test 7.4.1 (http://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#test-7-4-1);  actuellement les liens ne peuvent pas cibler les tests dans la page, car ces derniers sont pliés par défaut.
Je souhaite avoir une URL (avec un paramètre) qui affiche les tests par défaut (c.a.d tous les tests sont dépliés par défaut).

Merci.

**Comment by dzc34** [comment]
Bonjour,

Pour @Asqatasun nous avons le même besoin... :+1:  

Si besoin, nous pouvons donner 
un coup de main pour implanter une solution.

**Comment by Etat-Plateforme** [comment]
Merci pour votre commentaire.

Ce dysfonctionnement n’existe plus.

**Comment by dzc34** [comment]
> Ce dysfonctionnement n’existe plus.

si le problème persiste. 

procédure pour reproduire (par exemple pour le test 7.4.1) :
- ouvrir une "navigation privé" dans Firefox, Chrome, ...
- coller l'URL : http://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#test-7-4-1
- ce lien avec son ancre ne fonctionne pas 

par défauts, le test 7.4.1 n'est pas affiché 
et aucun mécanisme n'est utilisé pour déplier
ce test quand l'ancre #test-7-4-1 est utilisé dans l'URL.

**Comment by mkebri** [comment]
Nous avons résolu le problème avec  http://rgaa.tanaguru.com/fr/criteres.html#test-7-4-1

**Comment by dzc34** [comment]
> Nous avons résolu le problème 
@mkebri, la solution de tout déplier est effectivement la solution la plus facile pour résoudre ce problème.
Une PR sur le dépôt officiel ?

**Comment by dzc34** [comment]
à ce jour,  le dysfonctionnement n’existe effectivement plus.
merci.
