### ISSUE TITLE
Critère 1.1 : absence de test sur les SVG

### ISSUE THREAD

**Issue by n-chardon** [DISIC/rgaa_referentiel_3-2016#46]
Sur le critère 1.1,  il n'y a pas de test sur les SVG, contrairement à Accessiweb. On a par contre à la place un test sur les images réactives côté serveur, que j'aurai pensé être obsolètes ...

**Comment by OlivierNourry** [comment]
Bonjour Nicolas,
Je n’ai plus le souvenir des discussions qui ont mené à cette réécriture du 1.1 dans le RGAA, mais je devine pourquoi le test 1.1.4 sur les SVG dans AccessiWeb, a été supprimé dans le RGAA. C’est tout simplement qu’il entre en contradiction avec le 1.2.4: pour respecter le 1.1.4, il faut enfreindre le 1.2.4, et vice-versa. Avec la reformulation dans le RGAA, on couvre tous les cas de SVG, décorative ou non, via la pertinence de l’implémentation.

Quant aux images map coté serveur: elles sont toujours présentes dans la spec HTML5: https://www.w3.org/TR/html5/embedded-content-0.html#the-img-element <https://www.w3.org/TR/html5/embedded-content-0.html#the-img-element> (attribut ismap). Il est donc nécessaire d’en prévoir l’utilisation, même si, on est d’accord, c’est pas l’élément le plus commun qui soit...

**Comment by n-chardon** [comment]
Merci beaucoup pour ta réponse, je comprends mieux.
